INSERT INTO `websites` (`id`, `text`, `url`)
VALUES
      (NULL, 'Unicode snowman for you', 'http://unicodesnowmanforyou.com/'),
      (NULL, 'The UK, the greatest little country on earth and good friends with', 'http://brexit.de/'),
      (NULL, 'Can I fly a kite', 'https://www.caniflyakite.com/'),
      (NULL, 'Eel slap!', 'http://eelslap.com/'),
      (NULL, 'Ham rocks', 'https://ham.rocks/'),
      (NULL, 'My life is a loop :(', 'http://www.molleindustria.org/everydaythesamedream/everydaythesamedream.html'),
      (NULL, 'Movie in a minute', 'http://www.rinkworks.com/movieaminute/'),
      (NULL, 'Million dollar homepage', 'http://www.milliondollarhomepage.com/'),
      (NULL, 'Cow Spinner', 'http://spinnymeat.com/'),
      (NULL, 'Museum of selfies', 'http://museumofselfies.tumblr.com/'),
      (NULL, 'Chill out and watch some cat gifs', 'http://chilloutandwatchsomecatgifs.com/'),
      (NULL, 'Bouncy balls...', 'https://bouncyballs.org/'),
      (NULL, 'You crazy (cray cray)', 'http://youcraycray.com/'),
      (NULL, 'Flying Opera Pigs', 'http://flyingoperapigs.com/'),
      (NULL, 'Just a bell', 'http://hectorsalamanca.com/'),
      (NULL, 'Leak spin', 'http://leekspin.com/'),
      (NULL, 'D-E-F-I-N-I-T-E-L-Y', 'http://d-e-f-i-n-i-t-e-l-y.com/'),
      (NULL, 'Cat party', 'http://www.catparty.nonuigi.moe/'),
      (NULL, 'Bacon sizzling', 'http://www.baconsizzling.com/'),
      (NULL, 'Chat with yourself or watch...', 'http://www.chatwithyourself.com/'),
      (NULL, 'Pls pet doge', 'http://www.plspetdoge.com/'),
      (NULL, 'How secure is my password', 'https://howsecureismypassword.net/'),
      (NULL, 'Polar bear in a snow storm', 'http://www.polarbearinasnowstorm.com/'),
      (NULL, 'Dotted Lines', 'http://www.dottedlines.com/'),
      (NULL, 'Welcome to the internet setup!', 'https://html.house/jnftbgke.html'),
      (NULL, 'Test lol', 'https://www.testlol.com/');

